-- 더케어타임즈 테스트 기사 4/8: 문화 10건 (Supabase SQL 에디터에서 실행)
-- 제목에 [테스트]가 붙고, 본문은 원문 요약 + 출처 링크만 담는다 (원문 전문·사진은 가져오지 않음)
-- 사진은 레이아웃 확인용 무료 샘플 이미지(picsum.photos)
-- 여러 번 실행해도 같은 제목은 다시 넣지 않는다
-- 정식 오픈 전 삭제:  delete from articles where title like '[테스트]%';

with ctx as (
  select o.id as outlet_id,
         (select p.id from profiles p
           where p.outlet_id = o.id and p.role in ('admin', 'editor')
           order by p.created_at limit 1) as author_id
  from outlets o
  where o.domain = 'thecaretimes.com'
)
insert into articles (outlet_id, category_id, author_id, title, body, excerpt, thumbnail_url, status, published_at, is_featured, tags)
select ctx.outlet_id, c.id, ctx.author_id, v.title, v.body, v.excerpt, v.thumb, 'published', v.published_at, v.featured, array['테스트']
from ctx
cross join (values
  ('culture', '[테스트] 제16회 광주비엔날레 5일 개막…''변화와 실천'' 메시지 전달', '<p>제16회 광주비엔날레가 &#x27;너는 네 삶을 바꿔야 한다&#x27;를 주제로 막을 올려 11월 15일까지 이어진다. 22개국 43명·팀의 작가가 본전시와 파빌리온 등 광주 곳곳에서 작품을 선보인다.</p><p><em>※ 홈페이지 테스트용 게시물입니다. 원문 기사를 요약해 소개하며, 기사의 저작권은 뉴스핌에 있습니다.</em></p><p>출처: 뉴스핌 (2026-09-05) · <a href="https://www.newspim.com/news/view/20260905000050">원문 기사 보기</a></p>', '제16회 광주비엔날레가 ''너는 네 삶을 바꿔야 한다''를 주제로 막을 올려 11월 15일까지 이어진다. 22개국 43명·팀의 작가가 본전시와 파빌리온 등 광주 곳곳에서 작품을 선보인다.', 'https://picsum.photos/seed/care-culture-0/800/500', ('2026-09-05 09:00:00+09'::timestamptz + interval '0 minutes'), false),
  ('culture', '[테스트] 15만 명 발도장 찍고 간 키아프리즈…최고가는 25억 유영국 Work', '<p>키아프 서울과 프리즈 서울이 합산 관람객 약 15만 명을 기록하며 마무리됐다. 최고가 거래작은 갤러리현대가 내놓은 유영국의 &#x27;Work&#x27;로, 한국 작가 작품이 프리즈 서울 최고가에 오른 것은 5년 만이다.</p><p><em>※ 홈페이지 테스트용 게시물입니다. 원문 기사를 요약해 소개하며, 기사의 저작권은 한국경제에 있습니다.</em></p><p>출처: 한국경제 (2026-09-07) · <a href="https://www.hankyung.com/article/202609079064i">원문 기사 보기</a></p>', '키아프 서울과 프리즈 서울이 합산 관람객 약 15만 명을 기록하며 마무리됐다. 최고가 거래작은 갤러리현대가 내놓은 유영국의 ''Work''로, 한국 작가 작품이 프리즈 서울 최고가에 오른 것은 5년 만이다.', 'https://picsum.photos/seed/care-culture-1/800/500', ('2026-09-07 09:00:00+09'::timestamptz + interval '7 minutes'), false),
  ('culture', '[테스트] 올해 부산국제영화제 316편 상영…경쟁 부문 14편 초청, 대상작은 미국 아카데미 간다', '<p>제31회 부산국제영화제가 10월 6일부터 15일까지 열리며 316편을 상영한다. 개막작은 김종관 감독의 &#x27;낮과 밤은 서로에게&#x27;이고, 경쟁 부문 14편 중 대상작은 미국 아카데미 출품 자격을 얻는다.</p><p><em>※ 홈페이지 테스트용 게시물입니다. 원문 기사를 요약해 소개하며, 기사의 저작권은 서울신문에 있습니다.</em></p><p>출처: 서울신문 (2026-09-01) · <a href="https://www.seoul.co.kr/news/life/movie/2026/09/01/20260901500326">원문 기사 보기</a></p>', '제31회 부산국제영화제가 10월 6일부터 15일까지 열리며 316편을 상영한다. 개막작은 김종관 감독의 ''낮과 밤은 서로에게''이고, 경쟁 부문 14편 중 대상작은 미국 아카데미 출품 자격을 얻는다.', 'https://picsum.photos/seed/care-culture-2/800/500', ('2026-09-01 09:00:00+09'::timestamptz + interval '14 minutes'), false),
  ('culture', '[테스트] 9월, 전국이 미술관으로 변한다…‘2026 대한민국 미술축제’ 막 올라', '<p>문화체육관광부가 9월 한 달간 전국에서 &#x27;2026 대한민국 미술축제&#x27;를 연다. 광주·부산·제주 등 비엔날레와 서울 아트페어, 전국 96개 미술관이 함께하며 관람권 할인 등 혜택도 마련됐다.</p><p><em>※ 홈페이지 테스트용 게시물입니다. 원문 기사를 요약해 소개하며, 기사의 저작권은 이데일리에 있습니다.</em></p><p>출처: 이데일리 (2026-09-01) · <a href="https://www.edaily.co.kr/News/Read?newsId=03581766645575856">원문 기사 보기</a></p>', '문화체육관광부가 9월 한 달간 전국에서 ''2026 대한민국 미술축제''를 연다. 광주·부산·제주 등 비엔날레와 서울 아트페어, 전국 96개 미술관이 함께하며 관람권 할인 등 혜택도 마련됐다.', 'https://picsum.photos/seed/care-culture-3/800/500', ('2026-09-01 09:00:00+09'::timestamptz + interval '21 minutes'), false),
  ('culture', '[테스트] ''암살자(들)'', 추석 연휴 극장가 승자..''타짜: 벨제붑의 노래'' 2위 [★무비차트]', '<p>영화 &#x27;암살자(들)&#x27;이 추석 연휴 주말 박스오피스 정상에 오르며 누적 관객 150만 명을 넘겼다. &#x27;타짜: 벨제붑의 노래&#x27;가 뒤를 이어 2위를 차지했다.</p><p><em>※ 홈페이지 테스트용 게시물입니다. 원문 기사를 요약해 소개하며, 기사의 저작권은 스타뉴스에 있습니다.</em></p><p>출처: 스타뉴스 (2026-09-28) · <a href="https://www.starnewskorea.com/movie/2026/09/28/2026092807065177431">원문 기사 보기</a></p>', '영화 ''암살자(들)''이 추석 연휴 주말 박스오피스 정상에 오르며 누적 관객 150만 명을 넘겼다. ''타짜: 벨제붑의 노래''가 뒤를 이어 2위를 차지했다.', 'https://picsum.photos/seed/care-culture-4/800/500', ('2026-09-28 09:00:00+09'::timestamptz + interval '28 minutes'), false),
  ('culture', '[테스트] 안동국제탈춤페스티벌 개막…11일간 세계 각국 탈과 춤 한자리에', '<p>28회째를 맞은 안동국제탈춤페스티벌이 안동역과 원도심 일대에서 개막식을 열었다. &#x27;가면의 기억, 모두의 춤&#x27;을 주제로 10월 4일까지 국내외 탈춤과 가면 문화를 소개한다.</p><p><em>※ 홈페이지 테스트용 게시물입니다. 원문 기사를 요약해 소개하며, 기사의 저작권은 신아일보에 있습니다.</em></p><p>출처: 신아일보 (2026-09-27) · <a href="https://www.shinailbo.co.kr/news/articleView.html?idxno=5065913">원문 기사 보기</a></p>', '28회째를 맞은 안동국제탈춤페스티벌이 안동역과 원도심 일대에서 개막식을 열었다. ''가면의 기억, 모두의 춤''을 주제로 10월 4일까지 국내외 탈춤과 가면 문화를 소개한다.', 'https://picsum.photos/seed/care-culture-5/800/500', ('2026-09-27 09:00:00+09'::timestamptz + interval '35 minutes'), false),
  ('culture', '[테스트] 비파·마두금·비트박스까지…경계를 넓혀가는 국악관현악단의 축제', '<p>전국 국악관현악단 11곳이 참여하는 &#x27;2026 대한민국국악관현악축제&#x27;가 10월 6일부터 세종문화회관 M씨어터에서 열린다. 동아시아 전통악기와의 협연, 초연·위촉작 무대가 이어질 예정이다.</p><p><em>※ 홈페이지 테스트용 게시물입니다. 원문 기사를 요약해 소개하며, 기사의 저작권은 세계일보에 있습니다.</em></p><p>출처: 세계일보 (2026-09-26) · <a href="https://www.segye.com/newsView/20260926505336">원문 기사 보기</a></p>', '전국 국악관현악단 11곳이 참여하는 ''2026 대한민국국악관현악축제''가 10월 6일부터 세종문화회관 M씨어터에서 열린다. 동아시아 전통악기와의 협연, 초연·위촉작 무대가 이어질 예정이다.', 'https://picsum.photos/seed/care-culture-6/800/500', ('2026-09-26 09:00:00+09'::timestamptz + interval '42 minutes'), false),
  ('culture', '[테스트] 9월, 무형유산으로 물든다', '<p>국가유산청과 국가유산진흥원이 9월 중 국가무형유산 18개 종목의 공개행사를 연다. 국가의례와 전통예능 공연, 전통기술 시연 등이 전국 여러 곳에서 진행된다.</p><p><em>※ 홈페이지 테스트용 게시물입니다. 원문 기사를 요약해 소개하며, 기사의 저작권은 아시아경제에 있습니다.</em></p><p>출처: 아시아경제 (2026-08-26) · <a href="https://view.asiae.co.kr/article/2026082609360865450">원문 기사 보기</a></p>', '국가유산청과 국가유산진흥원이 9월 중 국가무형유산 18개 종목의 공개행사를 연다. 국가의례와 전통예능 공연, 전통기술 시연 등이 전국 여러 곳에서 진행된다.', 'https://picsum.photos/seed/care-culture-7/800/500', ('2026-08-26 09:00:00+09'::timestamptz + interval '49 minutes'), false),
  ('culture', '[테스트] 추석 연휴 막바지, 국가유산 나들이 가볼까', '<p>추석 연휴 동안 4대 궁과 종묘, 조선왕릉이 27일까지 무료로 개방되고 종묘는 예약 없이 둘러볼 수 있다. 국립중앙박물관과 국립민속박물관도 국악 공연과 전래놀이 등 가족 프로그램을 운영한다.</p><p><em>※ 홈페이지 테스트용 게시물입니다. 원문 기사를 요약해 소개하며, 기사의 저작권은 서울신문에 있습니다.</em></p><p>출처: 서울신문 (2026-09-26) · <a href="https://www.seoul.co.kr/news/life/cultural-heritage/2026/09/26/20260926500031">원문 기사 보기</a></p>', '추석 연휴 동안 4대 궁과 종묘, 조선왕릉이 27일까지 무료로 개방되고 종묘는 예약 없이 둘러볼 수 있다. 국립중앙박물관과 국립민속박물관도 국악 공연과 전래놀이 등 가족 프로그램을 운영한다.', 'https://picsum.photos/seed/care-culture-8/800/500', ('2026-09-26 09:00:00+09'::timestamptz + interval '56 minutes'), false),
  ('culture', '[테스트] ‘2026 천안 K-컬처박람회’ 9월 2일 개막', '<p>천안시가 9월 2일부터 6일까지 독립기념관에서 K-컬처박람회를 연다. K-푸드·K-웹툰·K-POP 전시관을 중심으로 수출상담회, AI 체험, 드론·레이저쇼 등을 준비했다.</p><p><em>※ 홈페이지 테스트용 게시물입니다. 원문 기사를 요약해 소개하며, 기사의 저작권은 서울신문에 있습니다.</em></p><p>출처: 서울신문 (2026-08-26) · <a href="https://www.seoul.co.kr/news/life/2026/08/26/20260826500176">원문 기사 보기</a></p>', '천안시가 9월 2일부터 6일까지 독립기념관에서 K-컬처박람회를 연다. K-푸드·K-웹툰·K-POP 전시관을 중심으로 수출상담회, AI 체험, 드론·레이저쇼 등을 준비했다.', 'https://picsum.photos/seed/care-culture-9/800/500', ('2026-08-26 09:00:00+09'::timestamptz + interval '63 minutes'), false)
) as v(slug, title, body, excerpt, thumb, published_at, featured)
join categories c on c.outlet_id = ctx.outlet_id and c.slug = v.slug
where not exists (select 1 from articles a where a.outlet_id = ctx.outlet_id and a.title = v.title);
