-- 더케어타임즈 테스트 기사 5/8: 보건복지 10건 (Supabase SQL 에디터에서 실행)
-- 제목에 [테스트]가 붙고, 본문은 원문 요약 + 출처 링크만 담는다 (원문 전문·사진은 가져오지 않음)
-- 사진은 레이아웃 확인용 무료 샘플 이미지(picsum.photos)
-- 여러 번 실행해도 같은 제목은 다시 넣지 않는다
-- 정식 오픈 전 삭제:  delete from articles where title like '[테스트]%';

with ctx as (
  select o.id as outlet_id,
         (select p.id from profiles p
           where p.outlet_id = o.id and p.role in ('admin', 'editor')
           order by p.created_at limit 1) as author_id
  from outlets o
  where o.domain = 'thecaretimes.net'
)
insert into articles (outlet_id, category_id, author_id, title, body, excerpt, thumbnail_url, status, published_at, is_featured, tags)
select ctx.outlet_id, c.id, ctx.author_id, v.title, v.body, v.excerpt, v.thumb, 'published', v.published_at, v.featured, array['테스트']
from ctx
cross join (values
  ('health-welfare', '[테스트] 2027년 복지부 예산 ‘152조’… 어디에 쓰이나', '<p>내년 보건복지부 예산안이 올해보다 8.2% 늘어난 148조여원으로 편성됐고, 미래대응기금 사업을 더하면 152조원대에 이른다. 기존 출산·양육 수당은 아이맞이지원금과 아동기본수당으로 통합·재편된다.</p><p><em>※ 홈페이지 테스트용 게시물입니다. 원문 기사를 요약해 소개하며, 기사의 저작권은 세계일보에 있습니다.</em></p><p>출처: 세계일보 (2026-09-04) · <a href="https://www.segye.com/newsView/20260904508422">원문 기사 보기</a></p>', '내년 보건복지부 예산안이 올해보다 8.2% 늘어난 148조여원으로 편성됐고, 미래대응기금 사업을 더하면 152조원대에 이른다. 기존 출산·양육 수당은 아이맞이지원금과 아동기본수당으로 통합·재편된다.', 'https://picsum.photos/seed/care-health-welfare-0/800/500', ('2026-09-04 09:00:00+09'::timestamptz + interval '0 minutes'), false),
  ('health-welfare', '[테스트] 저소득 노인 3만원 더…‘상박’ 뺀 반쪽 기초연금 개편', '<p>복지부 기초연금 개편안에서 수급 대상을 줄이는 방안은 사실상 제외됐다. 소득 하위 30% 노인은 월 3만원을 더 받고 그 위 구간은 물가 반영 인상 또는 동결되며, 부부 감액률도 낮아진다.</p><p><em>※ 홈페이지 테스트용 게시물입니다. 원문 기사를 요약해 소개하며, 기사의 저작권은 서울신문에 있습니다.</em></p><p>출처: 서울신문 (2026-09-01) · <a href="https://www.seoul.co.kr/news/society/2026/09/01/20260901500131">원문 기사 보기</a></p>', '복지부 기초연금 개편안에서 수급 대상을 줄이는 방안은 사실상 제외됐다. 소득 하위 30% 노인은 월 3만원을 더 받고 그 위 구간은 물가 반영 인상 또는 동결되며, 부부 감액률도 낮아진다.', 'https://picsum.photos/seed/care-health-welfare-1/800/500', ('2026-09-01 09:00:00+09'::timestamptz + interval '7 minutes'), false),
  ('health-welfare', '[테스트] 중증장애인 가구 의료급여 ‘부양의무자 기준’ 폐지 추진', '<p>복지부가 중앙의료급여심의위원회를 열어 2027~2029년 제4차 의료급여 기본계획 방향을 논의했다. 중증장애인 가구의 부양의무자 기준 폐지와 취약계층 간병비 지원 방안이 주요 검토 과제로 올랐다.</p><p><em>※ 홈페이지 테스트용 게시물입니다. 원문 기사를 요약해 소개하며, 기사의 저작권은 디지털타임스에 있습니다.</em></p><p>출처: 디지털타임스 (2026-09-08) · <a href="https://www.dt.co.kr/article/12082769">원문 기사 보기</a></p>', '복지부가 중앙의료급여심의위원회를 열어 2027~2029년 제4차 의료급여 기본계획 방향을 논의했다. 중증장애인 가구의 부양의무자 기준 폐지와 취약계층 간병비 지원 방안이 주요 검토 과제로 올랐다.', 'https://picsum.photos/seed/care-health-welfare-2/800/500', ('2026-09-08 09:00:00+09'::timestamptz + interval '14 minutes'), false),
  ('health-welfare', '[테스트] 먹거리·생필품 지원하는 ''그냥드림'' 전국 모든 시군구로 확대', '<p>소득 증빙 없이 먹거리와 생필품을 바로 지원하는 &#x27;그냥드림&#x27; 사업이 9월 중 전국 모든 시군구로 넓어진다. 기존 참여 175곳에 더해 나머지 55개 시군구가 순차적으로 합류한다.</p><p><em>※ 홈페이지 테스트용 게시물입니다. 원문 기사를 요약해 소개하며, 기사의 저작권은 파이낸셜뉴스에 있습니다.</em></p><p>출처: 파이낸셜뉴스 (2026-09-06) · <a href="https://www.fnnews.com/news/202609061253361409">원문 기사 보기</a></p>', '소득 증빙 없이 먹거리와 생필품을 바로 지원하는 ''그냥드림'' 사업이 9월 중 전국 모든 시군구로 넓어진다. 기존 참여 175곳에 더해 나머지 55개 시군구가 순차적으로 합류한다.', 'https://picsum.photos/seed/care-health-welfare-3/800/500', ('2026-09-06 09:00:00+09'::timestamptz + interval '21 minutes'), false),
  ('health-welfare', '[테스트] 복지부, 치매 조기 개입 강화…치매안심병원 25→50곳 확대', '<p>치매극복의 날 행사에서 복지부가 치매 조기 발견과 관리를 강화하겠다고 밝혔다. 치매안심병원을 2030년까지 50곳으로 늘리고, 지역에서 시행 중인 치매관리주치의제도 2028년까지 확대할 계획이다.</p><p><em>※ 홈페이지 테스트용 게시물입니다. 원문 기사를 요약해 소개하며, 기사의 저작권은 머니투데이에 있습니다.</em></p><p>출처: 머니투데이 (2026-09-21) · <a href="https://www.mt.co.kr/society/2026/09/21/2026092115312414364">원문 기사 보기</a></p>', '치매극복의 날 행사에서 복지부가 치매 조기 발견과 관리를 강화하겠다고 밝혔다. 치매안심병원을 2030년까지 50곳으로 늘리고, 지역에서 시행 중인 치매관리주치의제도 2028년까지 확대할 계획이다.', 'https://picsum.photos/seed/care-health-welfare-4/800/500', ('2026-09-21 09:00:00+09'::timestamptz + interval '28 minutes'), false),
  ('health-welfare', '[테스트] 정은경 복지부 장관 "자살, 사회적 문제…안전망 더 촘촘하게 구축"', '<p>정은경 복지부 장관이 자살을 개인이 아닌 사회 전체가 함께 풀어야 할 문제로 규정했다. 향후 5년간의 청사진인 제6차 자살예방기본계획을 통해 예방 안전망을 한층 강화하겠다는 방침을 밝혔다.</p><p><em>※ 홈페이지 테스트용 게시물입니다. 원문 기사를 요약해 소개하며, 기사의 저작권은 뉴스핌에 있습니다.</em></p><p>출처: 뉴스핌 (2026-09-10) · <a href="https://www.newspim.com/news/view/20260910000262">원문 기사 보기</a></p>', '정은경 복지부 장관이 자살을 개인이 아닌 사회 전체가 함께 풀어야 할 문제로 규정했다. 향후 5년간의 청사진인 제6차 자살예방기본계획을 통해 예방 안전망을 한층 강화하겠다는 방침을 밝혔다.', 'https://picsum.photos/seed/care-health-welfare-5/800/500', ('2026-09-10 09:00:00+09'::timestamptz + interval '35 minutes'), false),
  ('health-welfare', '[테스트] 독감 무료접종 14세까지 확대…9월 21일부터 순차 시작', '<p>질병관리청이 2026~2027절기 인플루엔자 국가예방접종을 9월 21일부터 내년 4월 30일까지 실시한다. 이번 절기부터 어린이 무료접종 대상이 14세까지 넓어지며, 대상군별로 차례로 접종이 시작된다.</p><p><em>※ 홈페이지 테스트용 게시물입니다. 원문 기사를 요약해 소개하며, 기사의 저작권은 청년의사에 있습니다.</em></p><p>출처: 청년의사 (2026-08-26) · <a href="http://www.docdocdoc.co.kr/news/articleView.html?idxno=3042121">원문 기사 보기</a></p>', '질병관리청이 2026~2027절기 인플루엔자 국가예방접종을 9월 21일부터 내년 4월 30일까지 실시한다. 이번 절기부터 어린이 무료접종 대상이 14세까지 넓어지며, 대상군별로 차례로 접종이 시작된다.', 'https://picsum.photos/seed/care-health-welfare-6/800/500', ('2026-08-26 09:00:00+09'::timestamptz + interval '42 minutes'), false),
  ('health-welfare', '[테스트] 100병상 이상 요양병원부터 간병비 급여화 추진', '<p>정부가 간병인을 직접 고용한 100병상 이상 의료중심 요양병원부터 간병비에 건강보험을 적용하는 방안을 공개했다. 간병 필요도가 높은 환자의 본인부담을 현행 100%에서 30% 안팎으로 낮추는 것이 핵심이다.</p><p><em>※ 홈페이지 테스트용 게시물입니다. 원문 기사를 요약해 소개하며, 기사의 저작권은 MBC에 있습니다.</em></p><p>출처: MBC (2026-07-28) · <a href="https://imnews.imbc.com/replay/2026/nw1200/article/6840584_36967.html">원문 기사 보기</a></p>', '정부가 간병인을 직접 고용한 100병상 이상 의료중심 요양병원부터 간병비에 건강보험을 적용하는 방안을 공개했다. 간병 필요도가 높은 환자의 본인부담을 현행 100%에서 30% 안팎으로 낮추는 것이 핵심이다.', 'https://picsum.photos/seed/care-health-welfare-7/800/500', ('2026-07-28 09:00:00+09'::timestamptz + interval '49 minutes'), false),
  ('health-welfare', '[테스트] 복지부, 발달장애인 돌봄 국가책임제 시행…보호자 부재 시, 24시간 돌봄 지원', '<p>복지부가 발달장애인 돌봄 국가책임제를 내놓고, 평일에만 운영되던 최중증 발달장애인 24시간 1:1 지원을 주말까지 넓히기로 했다. 공공후견과 재산관리 지원 등 권리 보호 장치도 강화한다.</p><p><em>※ 홈페이지 테스트용 게시물입니다. 원문 기사를 요약해 소개하며, 기사의 저작권은 뉴스핌에 있습니다.</em></p><p>출처: 뉴스핌 (2026-09-10) · <a href="https://www.newspim.com/news/view/20260910000203">원문 기사 보기</a></p>', '복지부가 발달장애인 돌봄 국가책임제를 내놓고, 평일에만 운영되던 최중증 발달장애인 24시간 1:1 지원을 주말까지 넓히기로 했다. 공공후견과 재산관리 지원 등 권리 보호 장치도 강화한다.', 'https://picsum.photos/seed/care-health-welfare-8/800/500', ('2026-09-10 09:00:00+09'::timestamptz + interval '56 minutes'), false),
  ('health-welfare', '[테스트] 반복 아동 학대 ‘강제 즉각분리’ 의무화 또 빠졌다', '<p>정부가 반복 아동학대 재발 방지 대책을 내놨지만, 1년 내 2회 이상 신고된 아동을 의무적으로 즉시 분리하는 규정은 담기지 않았다. 분리 보호를 우선 검토하도록 지침을 바꿨으나 현장 판단에 맡긴다는 한계가 지적됐다.</p><p><em>※ 홈페이지 테스트용 게시물입니다. 원문 기사를 요약해 소개하며, 기사의 저작권은 서울신문에 있습니다.</em></p><p>출처: 서울신문 (2026-09-02) · <a href="https://www.seoul.co.kr/news/society/health-welfare/2026/09/03/20260903010008">원문 기사 보기</a></p>', '정부가 반복 아동학대 재발 방지 대책을 내놨지만, 1년 내 2회 이상 신고된 아동을 의무적으로 즉시 분리하는 규정은 담기지 않았다. 분리 보호를 우선 검토하도록 지침을 바꿨으나 현장 판단에 맡긴다는 한계가 지적됐다.', 'https://picsum.photos/seed/care-health-welfare-9/800/500', ('2026-09-02 09:00:00+09'::timestamptz + interval '63 minutes'), false)
) as v(slug, title, body, excerpt, thumb, published_at, featured)
join categories c on c.outlet_id = ctx.outlet_id and c.slug = v.slug
where not exists (select 1 from articles a where a.outlet_id = ctx.outlet_id and a.title = v.title);
