-- 더케어타임즈 테스트 기사 6/8: 병원의료 10건 (Supabase SQL 에디터에서 실행)
-- 제목에 [테스트]가 붙고, 본문은 원문 요약 + 출처 링크만 담는다 (원문 전문·사진은 가져오지 않음)
-- 사진은 레이아웃 확인용 무료 샘플 이미지(picsum.photos)
-- 여러 번 실행해도 같은 제목은 다시 넣지 않는다
-- 정식 오픈 전 삭제:  delete from articles where title like '[테스트]%';

with ctx as (
  select o.id as outlet_id,
         (select p.id from profiles p
           where p.outlet_id = o.id and p.role in ('admin', 'editor')
           order by p.created_at limit 1) as author_id
  from outlets o
  where o.domain = 'thecaretimes.com'
)
insert into articles (outlet_id, category_id, author_id, title, body, excerpt, thumbnail_url, status, published_at, is_featured, tags)
select ctx.outlet_id, c.id, ctx.author_id, v.title, v.body, v.excerpt, v.thumb, 'published', v.published_at, v.featured, array['테스트']
from ctx
cross join (values
  ('medical', '[테스트] 2027학년도 지역의사 490명 첫 선발…지원자격은?', '<p>2027학년도부터 지역의사제가 시행돼 서울 외 의대에서 490명을 지역의사 전형으로 처음 선발한다. 지원자는 해당 지역 중·고교 재학 등 요건을 갖춰야 하며, 학비 지원을 받는 대신 면허 취득 후 10년간 지정 지역에서 복무해야 한다.</p><p><em>※ 홈페이지 테스트용 게시물입니다. 원문 기사를 요약해 소개하며, 기사의 저작권은 청년의사에 있습니다.</em></p><p>출처: 청년의사 (2026-09-03) · <a href="http://www.docdocdoc.co.kr/news/articleView.html?idxno=3042382">원문 기사 보기</a></p>', '2027학년도부터 지역의사제가 시행돼 서울 외 의대에서 490명을 지역의사 전형으로 처음 선발한다. 지원자는 해당 지역 중·고교 재학 등 요건을 갖춰야 하며, 학비 지원을 받는 대신 면허 취득 후 10년간 지정 지역에서 복무해야 한다.', 'https://picsum.photos/seed/care-medical-0/800/500', ('2026-09-03 09:00:00+09'::timestamptz + interval '0 minutes'), false),
  ('medical', '[테스트] 비급여 4개 중 3개 가격 올랐다…병원 따라 최대 2.8배 차이', '<p>국회 소병훈 의원이 심평원 자료를 분석한 결과, 전년과 비교 가능한 비급여 593개 항목 중 73.5%의 평균가격이 올랐다. 같은 진료라도 지역과 의료기관 종별에 따라 가격 차이가 최대 2.8배까지 벌어졌다.</p><p><em>※ 홈페이지 테스트용 게시물입니다. 원문 기사를 요약해 소개하며, 기사의 저작권은 청년의사에 있습니다.</em></p><p>출처: 청년의사 (2026-09-28) · <a href="https://www.docdocdoc.co.kr/news/articleView.html?idxno=3043084">원문 기사 보기</a></p>', '국회 소병훈 의원이 심평원 자료를 분석한 결과, 전년과 비교 가능한 비급여 593개 항목 중 73.5%의 평균가격이 올랐다. 같은 진료라도 지역과 의료기관 종별에 따라 가격 차이가 최대 2.8배까지 벌어졌다.', 'https://picsum.photos/seed/care-medical-1/800/500', ('2026-09-28 09:00:00+09'::timestamptz + interval '7 minutes'), false),
  ('medical', '[테스트] 동네의원 한국형 주치의 첫발…120곳서 시범사업', '<p>복지부가 9월 29일부터 전국 120개 동네의원에서 &#x27;지역사회 일차의료 혁신 시범사업&#x27;을 시작한다. 의사·간호사·영양사 등이 협력해 치료에서 예방·건강관리, 돌봄 연계까지 제공하는 한국형 주치의 모델이다.</p><p><em>※ 홈페이지 테스트용 게시물입니다. 원문 기사를 요약해 소개하며, 기사의 저작권은 메디칼타임즈에 있습니다.</em></p><p>출처: 메디칼타임즈 (2026-09-28) · <a href="https://www.medicaltimes.com/Main/News/NewsView.html?ID=1170889">원문 기사 보기</a></p>', '복지부가 9월 29일부터 전국 120개 동네의원에서 ''지역사회 일차의료 혁신 시범사업''을 시작한다. 의사·간호사·영양사 등이 협력해 치료에서 예방·건강관리, 돌봄 연계까지 제공하는 한국형 주치의 모델이다.', 'https://picsum.photos/seed/care-medical-2/800/500', ('2026-09-28 09:00:00+09'::timestamptz + interval '14 minutes'), false),
  ('medical', '[테스트] 국가 폐암검진 7년…드러난 사각지대 인공지능이 메울까', '<p>도입 7년째인 국가폐암검진이 나이와 흡연력 위주로 대상자를 정해 비흡연 고위험군 관리에 한계가 있다는 우려가 나왔다. 전문가들은 아시아의 비흡연 폐암 특성과 국내 결핵 병력 등을 반영한 검진체계 보완을 주문했다.</p><p><em>※ 홈페이지 테스트용 게시물입니다. 원문 기사를 요약해 소개하며, 기사의 저작권은 메디칼타임즈에 있습니다.</em></p><p>출처: 메디칼타임즈 (2026-09-28) · <a href="https://www.medicaltimes.com/Main/News/NewsView.html?ID=1170871">원문 기사 보기</a></p>', '도입 7년째인 국가폐암검진이 나이와 흡연력 위주로 대상자를 정해 비흡연 고위험군 관리에 한계가 있다는 우려가 나왔다. 전문가들은 아시아의 비흡연 폐암 특성과 국내 결핵 병력 등을 반영한 검진체계 보완을 주문했다.', 'https://picsum.photos/seed/care-medical-3/800/500', ('2026-09-28 09:00:00+09'::timestamptz + interval '21 minutes'), false),
  ('medical', '[테스트] 영천영대병원 응급실 운영 비상…이달 8차례 휴진 예고', '<p>영천시의회가 영남대의료원 측과 간담회를 열어 영천영대병원 응급실 운영난 해법을 논의했지만 뚜렷한 합의에는 이르지 못했다. 병원 측은 이어지는 적자와 응급의학과 전문의 채용난으로 안정적 운영이 어렵다고 밝혔다.</p><p><em>※ 홈페이지 테스트용 게시물입니다. 원문 기사를 요약해 소개하며, 기사의 저작권은 경북일보에 있습니다.</em></p><p>출처: 경북일보 (2026-09-09) · <a href="https://www.kyongbuk.co.kr/news/articleView.html?idxno=4083748">원문 기사 보기</a></p>', '영천시의회가 영남대의료원 측과 간담회를 열어 영천영대병원 응급실 운영난 해법을 논의했지만 뚜렷한 합의에는 이르지 못했다. 병원 측은 이어지는 적자와 응급의학과 전문의 채용난으로 안정적 운영이 어렵다고 밝혔다.', 'https://picsum.photos/seed/care-medical-4/800/500', ('2026-09-09 09:00:00+09'::timestamptz + interval '28 minutes'), false),
  ('medical', '[테스트] "적자 꼬리표 떼자"… 울주병원, 민간위탁 경영 ''승부수''', '<p>울산 울주군이 세운 공공병원인 울주병원이 민간 의료법인에 운영을 맡기는 방식으로 9월 진료를 시작했다. 지방의료원 다수가 만성 적자에 시달리는 가운데 민간 경영 역량을 활용하려는 시도로 주목받는다.</p><p><em>※ 홈페이지 테스트용 게시물입니다. 원문 기사를 요약해 소개하며, 기사의 저작권은 파이낸셜뉴스에 있습니다.</em></p><p>출처: 파이낸셜뉴스 (2026-09-06) · <a href="https://www.fnnews.com/news/202609061856284915">원문 기사 보기</a></p>', '울산 울주군이 세운 공공병원인 울주병원이 민간 의료법인에 운영을 맡기는 방식으로 9월 진료를 시작했다. 지방의료원 다수가 만성 적자에 시달리는 가운데 민간 경영 역량을 활용하려는 시도로 주목받는다.', 'https://picsum.photos/seed/care-medical-5/800/500', ('2026-09-06 09:00:00+09'::timestamptz + interval '35 minutes'), false),
  ('medical', '[테스트] “의료사고, 처벌만으론 해결 못해”… 개정 의료분쟁조정법 안착 방안 논의', '<p>2027년 5월 시행되는 개정 의료분쟁조정법의 정착 방안을 논의하는 학술행사가 열렸다. 참석자들은 환자 피해구제와 안정적 진료환경을 함께 보장하려면 책임보험, 의료사고 설명, 감정·조정 제도가 제대로 작동해야 한다고 짚었다.</p><p><em>※ 홈페이지 테스트용 게시물입니다. 원문 기사를 요약해 소개하며, 기사의 저작권은 법률신문에 있습니다.</em></p><p>출처: 법률신문 (2026-09-15) · <a href="https://www.lawtimes.co.kr/news/articleView.html?idxno=226427">원문 기사 보기</a></p>', '2027년 5월 시행되는 개정 의료분쟁조정법의 정착 방안을 논의하는 학술행사가 열렸다. 참석자들은 환자 피해구제와 안정적 진료환경을 함께 보장하려면 책임보험, 의료사고 설명, 감정·조정 제도가 제대로 작동해야 한다고 짚었다.', 'https://picsum.photos/seed/care-medical-6/800/500', ('2026-09-15 09:00:00+09'::timestamptz + interval '42 minutes'), false),
  ('medical', '[테스트] 의료진 부족→응급실 수용 곤란→올 4만건 넘어', '<p>올해 1~8월 전국 응급의료기관이 인력 부족을 이유로 환자 수용 곤란을 알린 건수가 4만4천여 건으로 이미 지난해 연간 수치를 넘었다. 병실 부족에 따른 수용 곤란은 크게 줄어 배후진료 인력 확보가 과제로 꼽혔다.</p><p><em>※ 홈페이지 테스트용 게시물입니다. 원문 기사를 요약해 소개하며, 기사의 저작권은 데일리메디에 있습니다.</em></p><p>출처: 데일리메디 (2026-09-23) · <a href="https://www.dailymedi.com/news/news_view.php?wr_id=940823">원문 기사 보기</a></p>', '올해 1~8월 전국 응급의료기관이 인력 부족을 이유로 환자 수용 곤란을 알린 건수가 4만4천여 건으로 이미 지난해 연간 수치를 넘었다. 병실 부족에 따른 수용 곤란은 크게 줄어 배후진료 인력 확보가 과제로 꼽혔다.', 'https://picsum.photos/seed/care-medical-7/800/500', ('2026-09-23 09:00:00+09'::timestamptz + interval '49 minutes'), false),
  ('medical', '[테스트] 전임의 실종…“교수 돼도 남는 건 당직·소송”', '<p>의정 갈등 이후 신규 전문의들이 전임의 과정을 외면하면서 주요 임상 학회들이 위기감을 드러냈다. 일부 대학병원 분과는 올해 전임의 지원자가 한 명도 없어 차세대 교수 인력 확보에 차질이 우려된다.</p><p><em>※ 홈페이지 테스트용 게시물입니다. 원문 기사를 요약해 소개하며, 기사의 저작권은 데일리메디에 있습니다.</em></p><p>출처: 데일리메디 (2026-09-28) · <a href="https://www.dailymedi.com/news/news_view.php?wr_id=940842">원문 기사 보기</a></p>', '의정 갈등 이후 신규 전문의들이 전임의 과정을 외면하면서 주요 임상 학회들이 위기감을 드러냈다. 일부 대학병원 분과는 올해 전임의 지원자가 한 명도 없어 차세대 교수 인력 확보에 차질이 우려된다.', 'https://picsum.photos/seed/care-medical-8/800/500', ('2026-09-28 09:00:00+09'::timestamptz + interval '56 minutes'), false),
  ('medical', '[테스트] 원자력병원, 국내 첫 로봇 두경부암수술 성공', '<p>원자력병원이 국산 수술로봇 &#x27;레보아이&#x27;로 설기저부암·상후두암 환자 3명에게 입을 통한 로봇수술을 시행했다고 밝혔다. 이 로봇을 활용한 해당 부위 절제술은 국내 처음이며, 환자들은 큰 합병증 없이 퇴원했다.</p><p><em>※ 홈페이지 테스트용 게시물입니다. 원문 기사를 요약해 소개하며, 기사의 저작권은 데일리메디에 있습니다.</em></p><p>출처: 데일리메디 (2026-09-23) · <a href="https://www.dailymedi.com/news/news_view.php?wr_id=940818">원문 기사 보기</a></p>', '원자력병원이 국산 수술로봇 ''레보아이''로 설기저부암·상후두암 환자 3명에게 입을 통한 로봇수술을 시행했다고 밝혔다. 이 로봇을 활용한 해당 부위 절제술은 국내 처음이며, 환자들은 큰 합병증 없이 퇴원했다.', 'https://picsum.photos/seed/care-medical-9/800/500', ('2026-09-23 09:00:00+09'::timestamptz + interval '63 minutes'), false)
) as v(slug, title, body, excerpt, thumb, published_at, featured)
join categories c on c.outlet_id = ctx.outlet_id and c.slug = v.slug
where not exists (select 1 from articles a where a.outlet_id = ctx.outlet_id and a.title = v.title);
