-- 더케어타임즈 테스트 기사 8/8: 돌봄산업 10건 (Supabase SQL 에디터에서 실행)
-- 제목에 [테스트]가 붙고, 본문은 원문 요약 + 출처 링크만 담는다 (원문 전문·사진은 가져오지 않음)
-- 사진은 레이아웃 확인용 무료 샘플 이미지(picsum.photos)
-- 여러 번 실행해도 같은 제목은 다시 넣지 않는다
-- 정식 오픈 전 삭제:  delete from articles where title like '[테스트]%';

with ctx as (
  select o.id as outlet_id,
         (select p.id from profiles p
           where p.outlet_id = o.id and p.role in ('admin', 'editor')
           order by p.created_at limit 1) as author_id
  from outlets o
  where o.domain = 'thecaretimes.net'
)
insert into articles (outlet_id, category_id, author_id, title, body, excerpt, thumbnail_url, status, published_at, is_featured, tags)
select ctx.outlet_id, c.id, ctx.author_id, v.title, v.body, v.excerpt, v.thumb, 'published', v.published_at, v.featured, array['테스트']
from ctx
cross join (values
  ('care-industry', '[테스트] 돌봄로봇 도입 시 5년간 8000억 효과…복지부, AI 돌봄 체계 대전환', '<p>정부가 AI와 돌봄로봇을 활용해 노인·장애인 돌봄 체계 전환을 추진하고 있다. 근력보조 돌봄로봇을 대규모로 운용할 경우 수천억 원대 사회적 가치가 발생한다는 측정 결과도 함께 공개됐다.</p><p><em>※ 홈페이지 테스트용 게시물입니다. 원문 기사를 요약해 소개하며, 기사의 저작권은 뉴스핌에 있습니다.</em></p><p>출처: 뉴스핌 (2026-09-16) · <a href="https://www.newspim.com/news/view/20260916000874">원문 기사 보기</a></p>', '정부가 AI와 돌봄로봇을 활용해 노인·장애인 돌봄 체계 전환을 추진하고 있다. 근력보조 돌봄로봇을 대규모로 운용할 경우 수천억 원대 사회적 가치가 발생한다는 측정 결과도 함께 공개됐다.', 'https://picsum.photos/seed/care-care-industry-0/800/500', ('2026-09-16 09:00:00+09'::timestamptz + interval '0 minutes'), false),
  ('care-industry', '[테스트] 국가통계로 처음 드러난 아이돌봄 ''엇박자''…부모는 저녁 찾는데 돌보미는 평일 낮 선호', '<p>아이돌봄서비스 실태조사에서 부모는 저녁 시간대 돌봄을 원하지만 돌보미는 평일 낮 근무를 선호하는 수급 불일치가 확인됐다. 연계 대기에 대한 만족도가 가장 낮았고 돌보미 처우 개선도 과제로 제시됐다.</p><p><em>※ 홈페이지 테스트용 게시물입니다. 원문 기사를 요약해 소개하며, 기사의 저작권은 뉴스핌에 있습니다.</em></p><p>출처: 뉴스핌 (2026-08-13) · <a href="https://www.newspim.com/news/view/20260813000355">원문 기사 보기</a></p>', '아이돌봄서비스 실태조사에서 부모는 저녁 시간대 돌봄을 원하지만 돌보미는 평일 낮 근무를 선호하는 수급 불일치가 확인됐다. 연계 대기에 대한 만족도가 가장 낮았고 돌보미 처우 개선도 과제로 제시됐다.', 'https://picsum.photos/seed/care-care-industry-1/800/500', ('2026-08-13 09:00:00+09'::timestamptz + interval '7 minutes'), false),
  ('care-industry', '[테스트] ''피터팬 아빠''의 걱정 다시는 없게…국가가 성인 발달장애인 책임진다', '<p>정부가 발달장애인 돌봄 국가책임제를 발표하고 성인 발달장애인 주간활동서비스를 단계적으로 늘리기로 했다. 최중증 발달장애인 24시간 통합돌봄 대상 확대와 지역사회 자립지원 본사업 전환도 포함됐다.</p><p><em>※ 홈페이지 테스트용 게시물입니다. 원문 기사를 요약해 소개하며, 기사의 저작권은 경향신문에 있습니다.</em></p><p>출처: 경향신문 (2026-09-10) · <a href="https://www.khan.co.kr/article/202609102105025/">원문 기사 보기</a></p>', '정부가 발달장애인 돌봄 국가책임제를 발표하고 성인 발달장애인 주간활동서비스를 단계적으로 늘리기로 했다. 최중증 발달장애인 24시간 통합돌봄 대상 확대와 지역사회 자립지원 본사업 전환도 포함됐다.', 'https://picsum.photos/seed/care-care-industry-2/800/500', ('2026-09-10 09:00:00+09'::timestamptz + interval '14 minutes'), false),
  ('care-industry', '[테스트] 대기번호만 1만9000번째…장애돌봄가족 휴식제도, 지원규모 여전히 부족', '<p>발달장애인 가족의 돌봄 부담을 덜기 위한 휴식지원 제도에 대기자가 2만 명 가까이 쌓여 있는 것으로 나타났다. 신청자 중 실제 이용자는 절반에 못 미쳐, 정부의 확대 계획도 수요에 비해 부족하다는 지적이다.</p><p><em>※ 홈페이지 테스트용 게시물입니다. 원문 기사를 요약해 소개하며, 기사의 저작권은 주간경향에 있습니다.</em></p><p>출처: 주간경향 (2026-09-21) · <a href="https://weekly.khan.co.kr/article/202609211654021/">원문 기사 보기</a></p>', '발달장애인 가족의 돌봄 부담을 덜기 위한 휴식지원 제도에 대기자가 2만 명 가까이 쌓여 있는 것으로 나타났다. 신청자 중 실제 이용자는 절반에 못 미쳐, 정부의 확대 계획도 수요에 비해 부족하다는 지적이다.', 'https://picsum.photos/seed/care-care-industry-3/800/500', ('2026-09-21 09:00:00+09'::timestamptz + interval '21 minutes'), false),
  ('care-industry', '[테스트] ''읍·면·동마다 전담 인력 1명'' 공언하더니···통합돌봄 시행 넉 달 지나도록 전국 151명뿐', '<p>통합돌봄 전면 시행 넉 달이 지났지만 읍·면·동 통합돌봄 전담 공무원은 전국 151명에 그쳤다. 대부분은 기존 업무와 겸직 중이며 전담 인력이 한 명도 없는 시·도도 여러 곳으로 파악됐다.</p><p><em>※ 홈페이지 테스트용 게시물입니다. 원문 기사를 요약해 소개하며, 기사의 저작권은 경향신문에 있습니다.</em></p><p>출처: 경향신문 (2026-08-21) · <a href="https://www.khan.co.kr/article/202608210600061/">원문 기사 보기</a></p>', '통합돌봄 전면 시행 넉 달이 지났지만 읍·면·동 통합돌봄 전담 공무원은 전국 151명에 그쳤다. 대부분은 기존 업무와 겸직 중이며 전담 인력이 한 명도 없는 시·도도 여러 곳으로 파악됐다.', 'https://picsum.photos/seed/care-care-industry-4/800/500', ('2026-08-21 09:00:00+09'::timestamptz + interval '28 minutes'), false),
  ('care-industry', '[테스트] 시민단체 "인천시 통합돌봄 사업비와 인프라·인력 확대해야"', '<p>인천 지역 시민단체 연대가 인천시에 통합돌봄 예산과 인프라, 전담 인력을 늘려야 한다고 요구했다. 단체는 현재 투입 규모로는 현장 안착이 어렵고 정부 예산안도 필요 규모에 크게 못 미친다고 주장했다.</p><p><em>※ 홈페이지 테스트용 게시물입니다. 원문 기사를 요약해 소개하며, 기사의 저작권은 이데일리에 있습니다.</em></p><p>출처: 이데일리 (2026-09-21) · <a href="https://edaily.co.kr/News/Read?mediaCodeNo=257&amp;newsId=04434566645582416">원문 기사 보기</a></p>', '인천 지역 시민단체 연대가 인천시에 통합돌봄 예산과 인프라, 전담 인력을 늘려야 한다고 요구했다. 단체는 현재 투입 규모로는 현장 안착이 어렵고 정부 예산안도 필요 규모에 크게 못 미친다고 주장했다.', 'https://picsum.photos/seed/care-care-industry-5/800/500', ('2026-09-21 09:00:00+09'::timestamptz + interval '35 minutes'), false),
  ('care-industry', '[테스트] 나주시, 전국 첫 AI 통합돌봄 ‘케어링크’ 시범 운영', '<p>전남 나주시가 돌봄 대상자와 가족, 제공기관, 행정을 하나로 잇는 AI 통합돌봄 플랫폼 시범사업을 9월 시작했다. 이용 주체별 앱으로 서비스 현황을 공유하고 AI 음성 안내, 말벗, 응급 호출 기능을 제공한다.</p><p><em>※ 홈페이지 테스트용 게시물입니다. 원문 기사를 요약해 소개하며, 기사의 저작권은 여성신문에 있습니다.</em></p><p>출처: 여성신문 (2026-09-02) · <a href="https://www.womennews.co.kr/news/articleView.html?idxno=281700">원문 기사 보기</a></p>', '전남 나주시가 돌봄 대상자와 가족, 제공기관, 행정을 하나로 잇는 AI 통합돌봄 플랫폼 시범사업을 9월 시작했다. 이용 주체별 앱으로 서비스 현황을 공유하고 AI 음성 안내, 말벗, 응급 호출 기능을 제공한다.', 'https://picsum.photos/seed/care-care-industry-6/800/500', ('2026-09-02 09:00:00+09'::timestamptz + interval '42 minutes'), false),
  ('care-industry', '[테스트] "교통·식대·명절수당 보장"…정부, 한국노총과 돌봄 분야 처우개선 본격 논의', '<p>정부가 한국노총과 요양보호사·장애인활동지원사 등 돌봄 종사자 처우개선 간담회를 열었다. 노조는 상설 협의체 구성과 교통비·식대·명절수당 보장을 요구했고, 정부는 장기근속 장려금 확대 등을 추진 중이라고 밝혔다.</p><p><em>※ 홈페이지 테스트용 게시물입니다. 원문 기사를 요약해 소개하며, 기사의 저작권은 뉴스핌에 있습니다.</em></p><p>출처: 뉴스핌 (2026-07-31) · <a href="https://www.newspim.com/news/view/20260731001178">원문 기사 보기</a></p>', '정부가 한국노총과 요양보호사·장애인활동지원사 등 돌봄 종사자 처우개선 간담회를 열었다. 노조는 상설 협의체 구성과 교통비·식대·명절수당 보장을 요구했고, 정부는 장기근속 장려금 확대 등을 추진 중이라고 밝혔다.', 'https://picsum.photos/seed/care-care-industry-7/800/500', ('2026-07-31 09:00:00+09'::timestamptz + interval '49 minutes'), false),
  ('care-industry', '[테스트] 중앙사회서비스원, ''2026 대한민국 사회서비스 박람회'' 개최', '<p>중앙사회서비스원이 사회서비스 전자바우처 도입 20주년을 맞아 서울 aT센터에서 사회서비스 박람회를 연다. 60여 개 기관이 참여해 돌봄 현장과 연결, 기술을 주제로 AI 낙상 감지 등 돌봄 기술을 선보인다.</p><p><em>※ 홈페이지 테스트용 게시물입니다. 원문 기사를 요약해 소개하며, 기사의 저작권은 서울신문에 있습니다.</em></p><p>출처: 서울신문 (2026-09-10) · <a href="https://www.seoul.co.kr/news/economy/2026/09/10/20260910500166">원문 기사 보기</a></p>', '중앙사회서비스원이 사회서비스 전자바우처 도입 20주년을 맞아 서울 aT센터에서 사회서비스 박람회를 연다. 60여 개 기관이 참여해 돌봄 현장과 연결, 기술을 주제로 AI 낙상 감지 등 돌봄 기술을 선보인다.', 'https://picsum.photos/seed/care-care-industry-8/800/500', ('2026-09-10 09:00:00+09'::timestamptz + interval '56 minutes'), false),
  ('care-industry', '[테스트] 시니어 2명 중 1명 시대···건설사, ''집'' 넘어 케어사업 키운다', '<p>고령 인구 확대에 맞춰 대형 건설사들이 주택 공급을 넘어 의료·돌봄 서비스를 결합한 시니어 케어 사업으로 영역을 넓히고 있다. 구매력 있는 시니어층 증가가 배경으로, AI 기반 건강관리 서비스 도입도 늘고 있다.</p><p><em>※ 홈페이지 테스트용 게시물입니다. 원문 기사를 요약해 소개하며, 기사의 저작권은 뉴스웨이에 있습니다.</em></p><p>출처: 뉴스웨이 (2026-09-23) · <a href="https://www.newsway.co.kr/news/view?ud=2026092309154570620">원문 기사 보기</a></p>', '고령 인구 확대에 맞춰 대형 건설사들이 주택 공급을 넘어 의료·돌봄 서비스를 결합한 시니어 케어 사업으로 영역을 넓히고 있다. 구매력 있는 시니어층 증가가 배경으로, AI 기반 건강관리 서비스 도입도 늘고 있다.', 'https://picsum.photos/seed/care-care-industry-9/800/500', ('2026-09-23 09:00:00+09'::timestamptz + interval '63 minutes'), false)
) as v(slug, title, body, excerpt, thumb, published_at, featured)
join categories c on c.outlet_id = ctx.outlet_id and c.slug = v.slug
where not exists (select 1 from articles a where a.outlet_id = ctx.outlet_id and a.title = v.title);
